// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnNAOfKhw6FmDmWl8f4rgQwWLrUDktlhU',
    appId: '1:383813993013:web:126d358fd7ce9e83fc677c',
    messagingSenderId: '383813993013',
    projectId: 'dogs-manes-list',
    authDomain: 'dogs-manes-list.firebaseapp.com',
    storageBucket: 'dogs-manes-list.appspot.com',
    measurementId: 'G-73YKYMVX66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3C894pp4LFGSCR4La6Re-bpHlSY0Nu9M',
    appId: '1:383813993013:android:4454161de75c8f70fc677c',
    messagingSenderId: '383813993013',
    projectId: 'dogs-manes-list',
    storageBucket: 'dogs-manes-list.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtMaAAiNrjO-JnEYqhYUnvEL5LYzDezPY',
    appId: '1:383813993013:ios:b4d379ba87d9a1e6fc677c',
    messagingSenderId: '383813993013',
    projectId: 'dogs-manes-list',
    storageBucket: 'dogs-manes-list.appspot.com',
    iosClientId: '383813993013-ne0iq6jlhqqp66aufao1is4p017ea1ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.arrayNames',
  );
}
